#!/bin/bash


echo " Salut c'est Neo , tu es actuellement dans la Matrice "

echo "All your base are belong to us!"


# Prepare container(s) and install dependencies
docker-compose build;
docker-compose run --rm test-api